// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.3
// source: helloworld.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GreeterClient is the client API for Greeter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GreeterClient interface {
	SendMailAction(ctx context.Context, opts ...grpc.CallOption) (Greeter_SendMailActionClient, error)
	FinishAction(ctx context.Context, opts ...grpc.CallOption) (Greeter_FinishActionClient, error)
	MonitoringData(ctx context.Context, opts ...grpc.CallOption) (Greeter_MonitoringDataClient, error)
	BlockInfo(ctx context.Context, opts ...grpc.CallOption) (Greeter_BlockInfoClient, error)
	MaliciousActionInfo(ctx context.Context, opts ...grpc.CallOption) (Greeter_MaliciousActionInfoClient, error)
}

type greeterClient struct {
	cc grpc.ClientConnInterface
}

func NewGreeterClient(cc grpc.ClientConnInterface) GreeterClient {
	return &greeterClient{cc}
}

func (c *greeterClient) SendMailAction(ctx context.Context, opts ...grpc.CallOption) (Greeter_SendMailActionClient, error) {
	stream, err := c.cc.NewStream(ctx, &Greeter_ServiceDesc.Streams[0], "/Greeter/SendMailAction", opts...)
	if err != nil {
		return nil, err
	}
	x := &greeterSendMailActionClient{stream}
	return x, nil
}

type Greeter_SendMailActionClient interface {
	Send(*Request) error
	Recv() (*MaliReply, error)
	grpc.ClientStream
}

type greeterSendMailActionClient struct {
	grpc.ClientStream
}

func (x *greeterSendMailActionClient) Send(m *Request) error {
	return x.ClientStream.SendMsg(m)
}

func (x *greeterSendMailActionClient) Recv() (*MaliReply, error) {
	m := new(MaliReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *greeterClient) FinishAction(ctx context.Context, opts ...grpc.CallOption) (Greeter_FinishActionClient, error) {
	stream, err := c.cc.NewStream(ctx, &Greeter_ServiceDesc.Streams[1], "/Greeter/FinishAction", opts...)
	if err != nil {
		return nil, err
	}
	x := &greeterFinishActionClient{stream}
	return x, nil
}

type Greeter_FinishActionClient interface {
	Send(*ActionInfo) error
	CloseAndRecv() (*Reply, error)
	grpc.ClientStream
}

type greeterFinishActionClient struct {
	grpc.ClientStream
}

func (x *greeterFinishActionClient) Send(m *ActionInfo) error {
	return x.ClientStream.SendMsg(m)
}

func (x *greeterFinishActionClient) CloseAndRecv() (*Reply, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(Reply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *greeterClient) MonitoringData(ctx context.Context, opts ...grpc.CallOption) (Greeter_MonitoringDataClient, error) {
	stream, err := c.cc.NewStream(ctx, &Greeter_ServiceDesc.Streams[2], "/Greeter/MonitoringData", opts...)
	if err != nil {
		return nil, err
	}
	x := &greeterMonitoringDataClient{stream}
	return x, nil
}

type Greeter_MonitoringDataClient interface {
	Send(*Monitoring) error
	CloseAndRecv() (*Reply, error)
	grpc.ClientStream
}

type greeterMonitoringDataClient struct {
	grpc.ClientStream
}

func (x *greeterMonitoringDataClient) Send(m *Monitoring) error {
	return x.ClientStream.SendMsg(m)
}

func (x *greeterMonitoringDataClient) CloseAndRecv() (*Reply, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(Reply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *greeterClient) BlockInfo(ctx context.Context, opts ...grpc.CallOption) (Greeter_BlockInfoClient, error) {
	stream, err := c.cc.NewStream(ctx, &Greeter_ServiceDesc.Streams[3], "/Greeter/BlockInfo", opts...)
	if err != nil {
		return nil, err
	}
	x := &greeterBlockInfoClient{stream}
	return x, nil
}

type Greeter_BlockInfoClient interface {
	Send(*BlockInfo) error
	CloseAndRecv() (*Reply, error)
	grpc.ClientStream
}

type greeterBlockInfoClient struct {
	grpc.ClientStream
}

func (x *greeterBlockInfoClient) Send(m *BlockInfo) error {
	return x.ClientStream.SendMsg(m)
}

func (x *greeterBlockInfoClient) CloseAndRecv() (*Reply, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(Reply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *greeterClient) MaliciousActionInfo(ctx context.Context, opts ...grpc.CallOption) (Greeter_MaliciousActionInfoClient, error) {
	stream, err := c.cc.NewStream(ctx, &Greeter_ServiceDesc.Streams[4], "/Greeter/MaliciousActionInfo", opts...)
	if err != nil {
		return nil, err
	}
	x := &greeterMaliciousActionInfoClient{stream}
	return x, nil
}

type Greeter_MaliciousActionInfoClient interface {
	Send(*Request) error
	CloseAndRecv() (*MaliciousAction, error)
	grpc.ClientStream
}

type greeterMaliciousActionInfoClient struct {
	grpc.ClientStream
}

func (x *greeterMaliciousActionInfoClient) Send(m *Request) error {
	return x.ClientStream.SendMsg(m)
}

func (x *greeterMaliciousActionInfoClient) CloseAndRecv() (*MaliciousAction, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(MaliciousAction)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GreeterServer is the server API for Greeter service.
// All implementations must embed UnimplementedGreeterServer
// for forward compatibility
type GreeterServer interface {
	SendMailAction(Greeter_SendMailActionServer) error
	FinishAction(Greeter_FinishActionServer) error
	MonitoringData(Greeter_MonitoringDataServer) error
	BlockInfo(Greeter_BlockInfoServer) error
	MaliciousActionInfo(Greeter_MaliciousActionInfoServer) error
	mustEmbedUnimplementedGreeterServer()
}

// UnimplementedGreeterServer must be embedded to have forward compatible implementations.
type UnimplementedGreeterServer struct {
}

func (UnimplementedGreeterServer) SendMailAction(Greeter_SendMailActionServer) error {
	return status.Errorf(codes.Unimplemented, "method SendMailAction not implemented")
}
func (UnimplementedGreeterServer) FinishAction(Greeter_FinishActionServer) error {
	return status.Errorf(codes.Unimplemented, "method FinishAction not implemented")
}
func (UnimplementedGreeterServer) MonitoringData(Greeter_MonitoringDataServer) error {
	return status.Errorf(codes.Unimplemented, "method MonitoringData not implemented")
}
func (UnimplementedGreeterServer) BlockInfo(Greeter_BlockInfoServer) error {
	return status.Errorf(codes.Unimplemented, "method BlockInfo not implemented")
}
func (UnimplementedGreeterServer) MaliciousActionInfo(Greeter_MaliciousActionInfoServer) error {
	return status.Errorf(codes.Unimplemented, "method MaliciousActionInfo not implemented")
}
func (UnimplementedGreeterServer) mustEmbedUnimplementedGreeterServer() {}

// UnsafeGreeterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GreeterServer will
// result in compilation errors.
type UnsafeGreeterServer interface {
	mustEmbedUnimplementedGreeterServer()
}

func RegisterGreeterServer(s grpc.ServiceRegistrar, srv GreeterServer) {
	s.RegisterService(&Greeter_ServiceDesc, srv)
}

func _Greeter_SendMailAction_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GreeterServer).SendMailAction(&greeterSendMailActionServer{stream})
}

type Greeter_SendMailActionServer interface {
	Send(*MaliReply) error
	Recv() (*Request, error)
	grpc.ServerStream
}

type greeterSendMailActionServer struct {
	grpc.ServerStream
}

func (x *greeterSendMailActionServer) Send(m *MaliReply) error {
	return x.ServerStream.SendMsg(m)
}

func (x *greeterSendMailActionServer) Recv() (*Request, error) {
	m := new(Request)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Greeter_FinishAction_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GreeterServer).FinishAction(&greeterFinishActionServer{stream})
}

type Greeter_FinishActionServer interface {
	SendAndClose(*Reply) error
	Recv() (*ActionInfo, error)
	grpc.ServerStream
}

type greeterFinishActionServer struct {
	grpc.ServerStream
}

func (x *greeterFinishActionServer) SendAndClose(m *Reply) error {
	return x.ServerStream.SendMsg(m)
}

func (x *greeterFinishActionServer) Recv() (*ActionInfo, error) {
	m := new(ActionInfo)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Greeter_MonitoringData_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GreeterServer).MonitoringData(&greeterMonitoringDataServer{stream})
}

type Greeter_MonitoringDataServer interface {
	SendAndClose(*Reply) error
	Recv() (*Monitoring, error)
	grpc.ServerStream
}

type greeterMonitoringDataServer struct {
	grpc.ServerStream
}

func (x *greeterMonitoringDataServer) SendAndClose(m *Reply) error {
	return x.ServerStream.SendMsg(m)
}

func (x *greeterMonitoringDataServer) Recv() (*Monitoring, error) {
	m := new(Monitoring)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Greeter_BlockInfo_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GreeterServer).BlockInfo(&greeterBlockInfoServer{stream})
}

type Greeter_BlockInfoServer interface {
	SendAndClose(*Reply) error
	Recv() (*BlockInfo, error)
	grpc.ServerStream
}

type greeterBlockInfoServer struct {
	grpc.ServerStream
}

func (x *greeterBlockInfoServer) SendAndClose(m *Reply) error {
	return x.ServerStream.SendMsg(m)
}

func (x *greeterBlockInfoServer) Recv() (*BlockInfo, error) {
	m := new(BlockInfo)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Greeter_MaliciousActionInfo_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GreeterServer).MaliciousActionInfo(&greeterMaliciousActionInfoServer{stream})
}

type Greeter_MaliciousActionInfoServer interface {
	SendAndClose(*MaliciousAction) error
	Recv() (*Request, error)
	grpc.ServerStream
}

type greeterMaliciousActionInfoServer struct {
	grpc.ServerStream
}

func (x *greeterMaliciousActionInfoServer) SendAndClose(m *MaliciousAction) error {
	return x.ServerStream.SendMsg(m)
}

func (x *greeterMaliciousActionInfoServer) Recv() (*Request, error) {
	m := new(Request)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Greeter_ServiceDesc is the grpc.ServiceDesc for Greeter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Greeter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Greeter",
	HandlerType: (*GreeterServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SendMailAction",
			Handler:       _Greeter_SendMailAction_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "FinishAction",
			Handler:       _Greeter_FinishAction_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "MonitoringData",
			Handler:       _Greeter_MonitoringData_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "BlockInfo",
			Handler:       _Greeter_BlockInfo_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "MaliciousActionInfo",
			Handler:       _Greeter_MaliciousActionInfo_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "helloworld.proto",
}
